name: Dougclectica Rebooted
title: Dougclectica Rebooted
author: Doug Breaux
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Topics from my software development meanderings.
show_excerpts: true

baseurl: ""
url: "https://dougbreaux.github.io"

#theme: minima
#github_username: dougbreaux
#linkedin_username: dougbreaux
#rss: rss

# to get latest master
remote_theme: jekyll/minima

# https://github.com/jekyll/minima#available-skins
# solarized adjusts to user's dark/light system theme
# use solarized-light or -dark to force one
minima:
  skin: solarized-light
  social_links:
    github: dougbreaux
    stackoverflow: "796761"
    linkedin: dougbreaux
  
#paginate: 10

kramdown:
#    syntax_highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false

gems:

# fake Disqus so can do utterances comments without changing base Minima post.html
disqus:
  shortname: fake_disqus_utterances
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 #- jekyll-paginate

prose:
  rooturl: '_posts'
  siteurl: 'https://dougbreaux.github.io/'
  media: 'assets'
