name: Dougclectica Rebooted, on GitHub
author: Doug Breaux

theme: jekyll-theme-leap-day

paginate: 10

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
