name: Dougclectica Rebooted, on GitHub
author: Doug Breaux

#remote-theme: agusmakmun/agusmakmun.github.io

theme: minima

paginate: 15

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false
