name: Dougclectica Rebooted
author: Doug Breaux

theme: minima
title: Dougclectica Rebooted
author: Doug Breaux
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Topics from my software development meanderings.
show_excerpts: true
rss: rss

paginate: 15

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false
