name: Dougclectica Rebooted, on GitHub
author: Doug Breaux

theme: minima
show_excerpts: true
rss: rss

paginate: 15

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false
