name: Dougclectica Rebooted, on GitHub
author: Doug Breaux

#remote-theme: agusmakmun/agusmakmun.github.io
#remote-theme: "jekyll/minima"
theme: minimal
#remote_theme: "mmistakes/minimal-mistakes@4.17.2"

paginate: 15

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false
