name: Dougclectica Rebooted
title: Dougclectica Rebooted
author: Doug Breaux
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Topics from my software development meanderings.
show_excerpts: true

theme: minima

rss: rss
github_username: dougbreaux
linkedin_username: dougbreaux
stackoverflow_username: dbreaux

paginate: 15

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false

plugins:
 - jekyll-feed
 - jekyll-seo-tag
