name: Dougclectica Rebooted
title: Dougclectica Rebooted
author: Doug Breaux
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Topics from my software development meanderings.
show_excerpts: true

#theme: minima
# to get latest master
remote_theme: jekyll/minima

rss: rss

minima:
  social_links:
    github: dougbreaux
    stackoverflow: "796761"
    linkedin: dougbreaux
  
#github_username: dougbreaux
#linkedin_username: dougbreaux

#paginate: 15
#paginate_path: posts/page:num/

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false

gems:
#  - jekyll-paginate

plugins:
# - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
 # for remote themes
 #- jekyll-remote-theme

prose:
  rooturl: '_posts'
  siteurl: 'https://dougbreaux.github.io/'
  media: 'assets'
